### ISSUE TITLE
FR: display CCA based upon keywords set

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-custom-content-areas#2]
filter the loop content to determine if the "keyword" or "phrase" is found in the content.  If so, then display the CCA in the defined location.

**Comment by JiveDig** [comment]
I'm thinking a text or textarea field where you comma separate keyword strings to check, or one per-link if textarea.

*Concerns:*
- Multiple strings to check. Should this be "or" or "and"? I'm thinking default to "or" for now. Maybe add a filter or setting later.
- Exact string matches. `Broccoli` vs `broccoli` would not be a match. Maybe we should strip everything to lowercase and check that way? `strtolower()` on the keywords and the content.

**Comment by JiveDig** [comment]
We should parse shortcodes first, then `strip_tags()` so it's only checking the actual text.

**Comment by JiveDig** [comment]
This is getting added now. It's all case-insensitive and strips everything to lowercase. If you have multiple strings it checks for any of them, it doesn't require all.

**Comment by JiveDig** [comment]
My content has `Broccoli.`, my keyword search field is `brocColi,  sieve` and it matched correctly.

**Comment by JiveDig** [comment]
The only times this will get weird is when it's multiple words. If you want "Broccoli casserole" it needs to be spelled exactly like that, and with only 1 space between the words. I think that's okay though.
